name             'webapp_base_box'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures webapp_base_box'
long_description 'Installs/Configures webapp_base_box'
version          '0.1.0'
